version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "DB"
    ports:
      - "33406:3306"
    volumes:
      - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
      - "./mysql-dump:/docker-entrypoint-initdb.d"
  springboot-api:
    image: springboot-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8031:8080"
    environment:
      dbhost: "3.142.146.96"
      dbport: 33406
      dbname: "DB"
      dbuser: "root"
      dbpass: "123456"
    restart: on-failure
