version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: "DB"
    ports:
      - "31003:31003"
    volumes:
      - "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"
      - "./mysql-dump:/docker-entrypoint-initdb.d"
  springboot-api:
    image: springboot-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8031:8080"
    environment:
      dbhost: "mysqldb"
      dbport: 31003
      dbname: "DB"
      dbuser: "root"
      dbpass: "123456"
      oktaIssuerUrl: ""
      oktaClientId: ""
      oktaClientSecret: ""
    restart: on-failure
    links:
      - mysqldb
    depends_on:
      - mysqldb
